name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Clean distribution directory
      run: |
        rm -rf dist/
        mkdir -p dist/
        
    - name: Install build dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    
    - name: Build package
      run: |
        # Make sure we're using the correct setup.py with version 0.3.0
        python -m build
        
    - name: Verify package metadata
      run: |
        python -m twine check dist/* || echo "Warning: metadata validation issues, but proceeding anyway"
      
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true
        verbose: true
